config/routes.rb
Lnknzr::Application.routes.draw do
  resources :links

  devise_for :users

  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'impressum' => 'pages#impressum'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description
  # attr_accessible :title, :body
  validates :description, presence: true

  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authenticate_user!
  # GET /links
  # GET /links.json
  def index
    @links = current_user.links.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = current_user.links.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = current_user.links.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = current_user.links.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = current_user.links.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = current_user.links.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@home_page = true
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
<%= link_to "Home", root_path %>
<%= link_to "Impressum", impressum_path %>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Lnknzr", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to "Home", root_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "LogIn", new_user_session_path %></li>
          <% end %>
        </ul>
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= @home_page ? 'homepage_html' : ''%>">
	<head>
	  	<title>Lnknzr - organize your links</title>
		  <%= stylesheet_link_tag    "application", :media => "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body class="<%= @home_page ? 'homepage' : ''%>">

		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>
   			<%= yield %>
   			<% if current_page?(root_url) %>
   				
   			<% else %>
					<%= render 'layouts/footer' %>
			<% end %>
		</div>
	</body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for(@link, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
	<%= f.input :description %>

  	<div class="form-actions">
    	<%= f.button :submit, class: "btn btn-primary" %>
  	</div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table class="table table-striped">
  <tr>
    <thead>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
  </tr>

  <tbody>
    <% @links.each do |link| %>
    <tr>
      <td><%= link.description %></td>
      <td><%= link_to 'Show', link %></td>
      <td><%= link_to 'Edit', edit_link_path(link) %></td>
      <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
				<%= @link.description %>
			</p>
			<%= link_to 'Edit', edit_link_path(@link) %> |
			<%= link_to 'Back', links_path %>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
About

app/views/pages/home.html.erb
<div class="row">
	<div class="home">
	  <h1>I love chaos <br />but only up to a certain degree ;-)</h1>
	  <h2>Lnknzr - helps organizing your links</h2>
	  <p>
	  	<%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-large btn-success" %>
	  </p>
  </div>
</div>

app/views/pages/impressum.html.erb
Bildnachweis
view7 / photocase.com